# megatron actor config, inheriting from trainer/config/actor/actor.yaml
defaults:
  # megatron optimizer config
  - ../optim@optim: megatron

  # megatron engine config
  - ../engine@megatron: megatron

  - actor

  # load the reference default config, then apply the fields in the current yaml
  - _self_

_target_: verl.workers.config.McoreActorConfig

strategy: megatron

# Whether to use chunked entropy computation
entropy_from_logits_with_chunking: False

# Chunk size used by chunked entropy computation
entropy_from_logits_chunk_size: 2048

megatron:
  entropy_from_logits_with_chunking: ${oc.select:actor_rollout_ref.actor.entropy_from_logits_with_chunking,False}
  entropy_from_logits_chunk_size: ${oc.select:actor_rollout_ref.actor.entropy_from_logits_chunk_size,2048}
